name: Docker CI/CD Pipeline
on:
  push:
    branches:
      - jaiye/gitactions-hospital-management
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.JAIYE_USERNAME }}
          password: ${{ secrets.JAIYE_PASSWORD }}

      - name: Build and push to Docker hub
        uses: docker/build-push-action@v5
        with:
          file: dockerfile
          context: .
          push: true
          tags: kingjaiye/hospital:${{ github.run_id }}
      - name: Login to the EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.JAIYE_HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.JAIYE_KEY }}
            port: ${{ secrets.PORT }}
            script: |
              docker stop hospital || true
              docker rm hospital || true
              docker pull ${{ secrets.JAIYE_USERNAME }}/hospital:${{ github.run_id }}
              docker run -d --name hospital -p 8000:80 ${{ secrets.JAIYE_USERNAME }}/hospital:${{ github.run_id }}